component: website
name: fullstack-frontend
app: fullstack-serverless-frontend

inputs:
  region: ${env:REGION}
  bucketName: fullstack-serverless-frontend
  protocol: https
  src:
    src: ./
    hook: npm run build
    dist: ./dist
    envPath: ./
    index: index.html
    error: index.html
  env:
    # get api url after below api service deployed.
    apiUrl: ${output:${stage}:${app}:fullstack-api.apigw.url}
