// 设置banner图
export const SET_ONE_LEVEL_PARTITIONS = "SET_ONE_LEVEL_PARTITIONS";
export const SET_RANKING_VIDEOS = "SET_RANKING_VIDEOS"
export const SET_RANKING_PARTITIONS = "SET_RANKING_PARTITIONS";